// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package i3c_reg_pkg;

  // Param list
  parameter int NumAlerts = 1;

  // Address widths within the block
  parameter int BlockAw = 12;

  // Number of registers for every interface
  parameter int NumRegs = 8;

  // Alert indices
  typedef enum int {
    AlertFatalFaultIdx = 0
  } i3c_alert_idx_t;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    logic        q;
  } i3c_reg2hw_intr_state_reg_t;

  typedef struct packed {
    logic        q;
  } i3c_reg2hw_intr_enable_reg_t;

  typedef struct packed {
    logic        q;
    logic        qe;
  } i3c_reg2hw_intr_test_reg_t;

  typedef struct packed {
    logic        q;
    logic        qe;
  } i3c_reg2hw_alert_test_reg_t;

  typedef struct packed {
    struct packed {
      logic [15:0] q;
    } clkdiv;
    struct packed {
      logic        q;
    } targ_en;
    struct packed {
      logic        q;
    } ctrl_en;
  } i3c_reg2hw_ctrl_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        re;
    } rx_idle;
    struct packed {
      logic        q;
      logic        re;
    } tx_idle;
  } i3c_reg2hw_status_reg_t;

  typedef struct packed {
    struct packed {
      logic [7:0]  q;
      logic        qe;
    } targ_rx_size;
    struct packed {
      logic [7:0]  q;
      logic        qe;
    } targ_tx_size;
    struct packed {
      logic [7:0]  q;
      logic        qe;
    } ctrl_rx_size;
    struct packed {
      logic [7:0]  q;
      logic        qe;
    } ctrl_tx_size;
  } i3c_reg2hw_buffer_config_reg_t;

  typedef struct packed {
    logic        d;
    logic        de;
  } i3c_hw2reg_intr_state_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
    } rx_idle;
    struct packed {
      logic        d;
    } tx_idle;
  } i3c_hw2reg_status_reg_t;

  typedef struct packed {
    struct packed {
      logic [7:0]  d;
    } rxlvl;
    struct packed {
      logic [7:0]  d;
    } txlvl;
  } i3c_hw2reg_buffer_status_reg_t;

  // Register -> HW type
  typedef struct packed {
    i3c_reg2hw_intr_state_reg_t intr_state; // [63:63]
    i3c_reg2hw_intr_enable_reg_t intr_enable; // [62:62]
    i3c_reg2hw_intr_test_reg_t intr_test; // [61:60]
    i3c_reg2hw_alert_test_reg_t alert_test; // [59:58]
    i3c_reg2hw_ctrl_reg_t ctrl; // [57:40]
    i3c_reg2hw_status_reg_t status; // [39:36]
    i3c_reg2hw_buffer_config_reg_t buffer_config; // [35:0]
  } i3c_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    i3c_hw2reg_intr_state_reg_t intr_state; // [19:18]
    i3c_hw2reg_status_reg_t status; // [17:16]
    i3c_hw2reg_buffer_status_reg_t buffer_status; // [15:0]
  } i3c_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] I3C_INTR_STATE_OFFSET = 12'h 0;
  parameter logic [BlockAw-1:0] I3C_INTR_ENABLE_OFFSET = 12'h 4;
  parameter logic [BlockAw-1:0] I3C_INTR_TEST_OFFSET = 12'h 8;
  parameter logic [BlockAw-1:0] I3C_ALERT_TEST_OFFSET = 12'h c;
  parameter logic [BlockAw-1:0] I3C_CTRL_OFFSET = 12'h 10;
  parameter logic [BlockAw-1:0] I3C_STATUS_OFFSET = 12'h 14;
  parameter logic [BlockAw-1:0] I3C_BUFFER_CONFIG_OFFSET = 12'h 18;
  parameter logic [BlockAw-1:0] I3C_BUFFER_STATUS_OFFSET = 12'h 1c;

  // Reset values for hwext registers and their fields
  parameter logic [0:0] I3C_INTR_TEST_RESVAL = 1'h 0;
  parameter logic [0:0] I3C_INTR_TEST_DONE_RESVAL = 1'h 0;
  parameter logic [0:0] I3C_ALERT_TEST_RESVAL = 1'h 0;
  parameter logic [0:0] I3C_ALERT_TEST_FATAL_FAULT_RESVAL = 1'h 0;
  parameter logic [1:0] I3C_STATUS_RESVAL = 2'h 3;
  parameter logic [0:0] I3C_STATUS_TX_IDLE_RESVAL = 1'h 1;
  parameter logic [0:0] I3C_STATUS_RX_IDLE_RESVAL = 1'h 1;
  parameter logic [23:0] I3C_BUFFER_STATUS_RESVAL = 24'h 0;

  // Window parameters
  parameter logic [BlockAw-1:0] I3C_BUFFER_OFFSET = 12'h 800;
  parameter int unsigned        I3C_BUFFER_SIZE   = 'h 800;
  parameter int unsigned        I3C_BUFFER_IDX    = 0;

  // Register index
  typedef enum int {
    I3C_INTR_STATE,
    I3C_INTR_ENABLE,
    I3C_INTR_TEST,
    I3C_ALERT_TEST,
    I3C_CTRL,
    I3C_STATUS,
    I3C_BUFFER_CONFIG,
    I3C_BUFFER_STATUS
  } i3c_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] I3C_PERMIT [8] = '{
    4'b 0001, // index[0] I3C_INTR_STATE
    4'b 0001, // index[1] I3C_INTR_ENABLE
    4'b 0001, // index[2] I3C_INTR_TEST
    4'b 0001, // index[3] I3C_ALERT_TEST
    4'b 1111, // index[4] I3C_CTRL
    4'b 0001, // index[5] I3C_STATUS
    4'b 1111, // index[6] I3C_BUFFER_CONFIG
    4'b 0111  // index[7] I3C_BUFFER_STATUS
  };

endpackage
