// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`

`include "prim_assert.sv"

module i3c_reg_top
  # (
    parameter bit          EnableRacl           = 1'b0,
    parameter bit          RaclErrorRsp         = 1'b1,
    parameter top_racl_pkg::racl_policy_sel_t RaclPolicySelVec[i3c_reg_pkg::NumRegs] =
      '{i3c_reg_pkg::NumRegs{0}}
  ) (
  input clk_i,
  input rst_ni,
  input  tlul_pkg::tl_h2d_t tl_i,
  output tlul_pkg::tl_d2h_t tl_o,

  // Output port for window
  output tlul_pkg::tl_h2d_t tl_win_o,
  input  tlul_pkg::tl_d2h_t tl_win_i,

  // To HW
  output i3c_reg_pkg::i3c_reg2hw_t reg2hw, // Write
  input  i3c_reg_pkg::i3c_hw2reg_t hw2reg, // Read

  // RACL interface
  input  top_racl_pkg::racl_policy_vec_t racl_policies_i,
  output top_racl_pkg::racl_error_log_t  racl_error_o,

  // Integrity check errors
  output logic intg_err_o
);

  import i3c_reg_pkg::* ;

  localparam int AW = 12;
  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [AW-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;
  logic reg_busy;

  tlul_pkg::tl_h2d_t tl_reg_h2d;
  tlul_pkg::tl_d2h_t tl_reg_d2h;


  // incoming payload check
  logic intg_err;
  tlul_cmd_intg_chk u_chk (
    .tl_i(tl_i),
    .err_o(intg_err)
  );

  // also check for spurious write enables
  logic reg_we_err;
  logic [7:0] reg_we_check;
  prim_reg_we_check #(
    .OneHotWidth(8)
  ) u_prim_reg_we_check (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .oh_i  (reg_we_check),
    .en_i  (reg_we && !addrmiss),
    .err_o (reg_we_err)
  );

  logic err_q;
  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      err_q <= '0;
    end else if (intg_err || reg_we_err) begin
      err_q <= 1'b1;
    end
  end

  // integrity error output is permanent and should be used for alert generation
  // register errors are transactional
  assign intg_err_o = err_q | intg_err | reg_we_err;

  // outgoing integrity generation
  tlul_pkg::tl_d2h_t tl_o_pre;
  tlul_rsp_intg_gen #(
    .EnableRspIntgGen(1),
    .EnableDataIntgGen(1)
  ) u_rsp_intg_gen (
    .tl_i(tl_o_pre),
    .tl_o(tl_o)
  );

  tlul_pkg::tl_h2d_t tl_socket_h2d [2];
  tlul_pkg::tl_d2h_t tl_socket_d2h [2];

  logic [0:0] reg_steer;

  // socket_1n connection
  assign tl_reg_h2d = tl_socket_h2d[1];
  assign tl_socket_d2h[1] = tl_reg_d2h;

  assign tl_win_o = tl_socket_h2d[0];
  assign tl_socket_d2h[0] = tl_win_i;

  // Create Socket_1n
  tlul_socket_1n #(
    .N            (2),
    .HReqPass     (1'b1),
    .HRspPass     (1'b1),
    .DReqPass     ({2{1'b1}}),
    .DRspPass     ({2{1'b1}}),
    .HReqDepth    (4'h0),
    .HRspDepth    (4'h0),
    .DReqDepth    ({2{4'h0}}),
    .DRspDepth    ({2{4'h0}}),
    .ExplicitErrs (1'b0)
  ) u_socket (
    .clk_i  (clk_i),
    .rst_ni (rst_ni),
    .tl_h_i (tl_i),
    .tl_h_o (tl_o_pre),
    .tl_d_o (tl_socket_h2d),
    .tl_d_i (tl_socket_d2h),
    .dev_select_i (reg_steer)
  );

  // Create steering logic
  always_comb begin
    reg_steer =
        tl_i.a_address[AW-1:0] inside {[2048:4095]} ? 1'd0 :
        // Default set to register
        1'd1;

    // Override this in case of an integrity error
    if (intg_err) begin
      reg_steer = 1'd1;
    end
  end

  tlul_adapter_reg #(
    .RegAw(AW),
    .RegDw(DW),
    .EnableDataIntgGen(0)
  ) u_reg_if (
    .clk_i  (clk_i),
    .rst_ni (rst_ni),

    .tl_i (tl_reg_h2d),
    .tl_o (tl_reg_d2h),

    .en_ifetch_i(prim_mubi_pkg::MuBi4False),
    .intg_error_o(),

    .we_o    (reg_we),
    .re_o    (reg_re),
    .addr_o  (reg_addr),
    .wdata_o (reg_wdata),
    .be_o    (reg_be),
    .busy_i  (reg_busy),
    .rdata_i (reg_rdata),
    // Translate RACL error to TLUL error if enabled
    .error_i (reg_error | (RaclErrorRsp & racl_error_o.valid))
  );

  // cdc oversampling signals

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = addrmiss | wr_err | intg_err;

  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic intr_state_qs;
  logic intr_enable_we;
  logic intr_enable_qs;
  logic intr_enable_wd;
  logic intr_test_we;
  logic intr_test_wd;
  logic alert_test_we;
  logic alert_test_wd;
  logic ctrl_we;
  logic ctrl_ctrl_en_qs;
  logic ctrl_ctrl_en_wd;
  logic ctrl_targ_en_qs;
  logic ctrl_targ_en_wd;
  logic [15:0] ctrl_clkdiv_qs;
  logic [15:0] ctrl_clkdiv_wd;
  logic status_re;
  logic status_tx_idle_qs;
  logic status_rx_idle_qs;
  logic buffer_config_we;
  logic [7:0] buffer_config_ctrl_tx_size_qs;
  logic [7:0] buffer_config_ctrl_tx_size_wd;
  logic [7:0] buffer_config_ctrl_rx_size_qs;
  logic [7:0] buffer_config_ctrl_rx_size_wd;
  logic [7:0] buffer_config_targ_tx_size_qs;
  logic [7:0] buffer_config_targ_tx_size_wd;
  logic [7:0] buffer_config_targ_rx_size_qs;
  logic [7:0] buffer_config_targ_rx_size_wd;
  logic buffer_status_re;
  logic [7:0] buffer_status_txlvl_qs;
  logic [7:0] buffer_status_rxlvl_qs;

  // Register instances
  // R[intr_state]: V(False)
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRO),
    .RESVAL  (1'h1),
    .Mubi    (1'b0)
  ) u_intr_state (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (1'b0),
    .wd     ('0),

    // from internal hardware
    .de     (hw2reg.intr_state.de),
    .d      (hw2reg.intr_state.d),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.intr_state.q),
    .ds     (),

    // to register interface (read)
    .qs     (intr_state_qs)
  );


  // R[intr_enable]: V(False)
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_intr_enable (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (intr_enable_we),
    .wd     (intr_enable_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.intr_enable.q),
    .ds     (),

    // to register interface (read)
    .qs     (intr_enable_qs)
  );


  // R[intr_test]: V(True)
  logic intr_test_qe;
  logic [0:0] intr_test_flds_we;
  assign intr_test_qe = &intr_test_flds_we;
  prim_subreg_ext #(
    .DW    (1)
  ) u_intr_test (
    .re     (1'b0),
    .we     (intr_test_we),
    .wd     (intr_test_wd),
    .d      ('0),
    .qre    (),
    .qe     (intr_test_flds_we[0]),
    .q      (reg2hw.intr_test.q),
    .ds     (),
    .qs     ()
  );
  assign reg2hw.intr_test.qe = intr_test_qe;


  // R[alert_test]: V(True)
  logic alert_test_qe;
  logic [0:0] alert_test_flds_we;
  assign alert_test_qe = &alert_test_flds_we;
  prim_subreg_ext #(
    .DW    (1)
  ) u_alert_test (
    .re     (1'b0),
    .we     (alert_test_we),
    .wd     (alert_test_wd),
    .d      ('0),
    .qre    (),
    .qe     (alert_test_flds_we[0]),
    .q      (reg2hw.alert_test.q),
    .ds     (),
    .qs     ()
  );
  assign reg2hw.alert_test.qe = alert_test_qe;


  // R[ctrl]: V(False)
  //   F[ctrl_en]: 0:0
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_ctrl_ctrl_en (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ctrl_we),
    .wd     (ctrl_ctrl_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.ctrl_en.q),
    .ds     (),

    // to register interface (read)
    .qs     (ctrl_ctrl_en_qs)
  );

  //   F[targ_en]: 1:1
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_ctrl_targ_en (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ctrl_we),
    .wd     (ctrl_targ_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.targ_en.q),
    .ds     (),

    // to register interface (read)
    .qs     (ctrl_targ_en_qs)
  );

  //   F[clkdiv]: 31:16
  prim_subreg #(
    .DW      (16),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (16'h0),
    .Mubi    (1'b0)
  ) u_ctrl_clkdiv (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ctrl_we),
    .wd     (ctrl_clkdiv_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.clkdiv.q),
    .ds     (),

    // to register interface (read)
    .qs     (ctrl_clkdiv_qs)
  );


  // R[status]: V(True)
  //   F[tx_idle]: 0:0
  prim_subreg_ext #(
    .DW    (1)
  ) u_status_tx_idle (
    .re     (status_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.status.tx_idle.d),
    .qre    (reg2hw.status.tx_idle.re),
    .qe     (),
    .q      (reg2hw.status.tx_idle.q),
    .ds     (),
    .qs     (status_tx_idle_qs)
  );

  //   F[rx_idle]: 1:1
  prim_subreg_ext #(
    .DW    (1)
  ) u_status_rx_idle (
    .re     (status_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.status.rx_idle.d),
    .qre    (reg2hw.status.rx_idle.re),
    .qe     (),
    .q      (reg2hw.status.rx_idle.q),
    .ds     (),
    .qs     (status_rx_idle_qs)
  );


  // R[buffer_config]: V(False)
  logic buffer_config_qe;
  logic [3:0] buffer_config_flds_we;
  prim_flop #(
    .Width(1),
    .ResetValue(0)
  ) u_buffer_config0_qe (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .d_i(&buffer_config_flds_we),
    .q_o(buffer_config_qe)
  );
  //   F[ctrl_tx_size]: 7:0
  prim_subreg #(
    .DW      (8),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (8'h0),
    .Mubi    (1'b0)
  ) u_buffer_config_ctrl_tx_size (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (buffer_config_we),
    .wd     (buffer_config_ctrl_tx_size_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (buffer_config_flds_we[0]),
    .q      (reg2hw.buffer_config.ctrl_tx_size.q),
    .ds     (),

    // to register interface (read)
    .qs     (buffer_config_ctrl_tx_size_qs)
  );
  assign reg2hw.buffer_config.ctrl_tx_size.qe = buffer_config_qe;

  //   F[ctrl_rx_size]: 15:8
  prim_subreg #(
    .DW      (8),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (8'h0),
    .Mubi    (1'b0)
  ) u_buffer_config_ctrl_rx_size (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (buffer_config_we),
    .wd     (buffer_config_ctrl_rx_size_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (buffer_config_flds_we[1]),
    .q      (reg2hw.buffer_config.ctrl_rx_size.q),
    .ds     (),

    // to register interface (read)
    .qs     (buffer_config_ctrl_rx_size_qs)
  );
  assign reg2hw.buffer_config.ctrl_rx_size.qe = buffer_config_qe;

  //   F[targ_tx_size]: 23:16
  prim_subreg #(
    .DW      (8),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (8'h0),
    .Mubi    (1'b0)
  ) u_buffer_config_targ_tx_size (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (buffer_config_we),
    .wd     (buffer_config_targ_tx_size_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (buffer_config_flds_we[2]),
    .q      (reg2hw.buffer_config.targ_tx_size.q),
    .ds     (),

    // to register interface (read)
    .qs     (buffer_config_targ_tx_size_qs)
  );
  assign reg2hw.buffer_config.targ_tx_size.qe = buffer_config_qe;

  //   F[targ_rx_size]: 31:24
  prim_subreg #(
    .DW      (8),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (8'h0),
    .Mubi    (1'b0)
  ) u_buffer_config_targ_rx_size (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (buffer_config_we),
    .wd     (buffer_config_targ_rx_size_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (buffer_config_flds_we[3]),
    .q      (reg2hw.buffer_config.targ_rx_size.q),
    .ds     (),

    // to register interface (read)
    .qs     (buffer_config_targ_rx_size_qs)
  );
  assign reg2hw.buffer_config.targ_rx_size.qe = buffer_config_qe;


  // R[buffer_status]: V(True)
  //   F[txlvl]: 7:0
  prim_subreg_ext #(
    .DW    (8)
  ) u_buffer_status_txlvl (
    .re     (buffer_status_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.buffer_status.txlvl.d),
    .qre    (),
    .qe     (),
    .q      (),
    .ds     (),
    .qs     (buffer_status_txlvl_qs)
  );

  //   F[rxlvl]: 23:16
  prim_subreg_ext #(
    .DW    (8)
  ) u_buffer_status_rxlvl (
    .re     (buffer_status_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.buffer_status.rxlvl.d),
    .qre    (),
    .qe     (),
    .q      (),
    .ds     (),
    .qs     (buffer_status_rxlvl_qs)
  );



  logic [7:0] addr_hit;
  top_racl_pkg::racl_role_vec_t racl_role_vec;
  top_racl_pkg::racl_role_t racl_role;

  logic [7:0] racl_addr_hit_read;
  logic [7:0] racl_addr_hit_write;

  if (EnableRacl) begin : gen_racl_role_logic
    // Retrieve RACL role from user bits and one-hot encode that for the comparison bitmap
    assign racl_role = top_racl_pkg::tlul_extract_racl_role_bits(tl_i.a_user.rsvd);

    prim_onehot_enc #(
      .OneHotWidth( $bits(top_racl_pkg::racl_role_vec_t) )
    ) u_racl_role_encode (
      .in_i ( racl_role     ),
      .en_i ( 1'b1          ),
      .out_o( racl_role_vec )
    );
  end else begin : gen_no_racl_role_logic
    assign racl_role     = '0;
    assign racl_role_vec = '0;
  end

  always_comb begin
    racl_addr_hit_read  = '0;
    racl_addr_hit_write = '0;
    addr_hit[0] = (reg_addr == I3C_INTR_STATE_OFFSET);
    addr_hit[1] = (reg_addr == I3C_INTR_ENABLE_OFFSET);
    addr_hit[2] = (reg_addr == I3C_INTR_TEST_OFFSET);
    addr_hit[3] = (reg_addr == I3C_ALERT_TEST_OFFSET);
    addr_hit[4] = (reg_addr == I3C_CTRL_OFFSET);
    addr_hit[5] = (reg_addr == I3C_STATUS_OFFSET);
    addr_hit[6] = (reg_addr == I3C_BUFFER_CONFIG_OFFSET);
    addr_hit[7] = (reg_addr == I3C_BUFFER_STATUS_OFFSET);

    if (EnableRacl) begin : gen_racl_hit
      for (int unsigned slice_idx = 0; slice_idx < 8; slice_idx++) begin
        racl_addr_hit_read[slice_idx] =
            addr_hit[slice_idx] & (|(racl_policies_i[RaclPolicySelVec[slice_idx]].read_perm
                                      & racl_role_vec));
        racl_addr_hit_write[slice_idx] =
            addr_hit[slice_idx] & (|(racl_policies_i[RaclPolicySelVec[slice_idx]].write_perm
                                      & racl_role_vec));
      end
    end else begin : gen_no_racl
      racl_addr_hit_read  = addr_hit;
      racl_addr_hit_write = addr_hit;
    end
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;
  // A valid address hit, access, but failed the RACL check
  assign racl_error_o.valid = |addr_hit & ((reg_re & ~|racl_addr_hit_read) |
                                           (reg_we & ~|racl_addr_hit_write));
  assign racl_error_o.request_address = top_pkg::TL_AW'(reg_addr);
  assign racl_error_o.racl_role       = racl_role;
  assign racl_error_o.overflow        = 1'b0;

  if (EnableRacl) begin : gen_racl_log
    assign racl_error_o.ctn_uid     = top_racl_pkg::tlul_extract_ctn_uid_bits(tl_i.a_user.rsvd);
    assign racl_error_o.read_access = tl_i.a_opcode == tlul_pkg::Get;
  end else begin : gen_no_racl_log
    assign racl_error_o.ctn_uid     = '0;
    assign racl_error_o.read_access = 1'b0;
  end

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((racl_addr_hit_write[0] & (|(I3C_PERMIT[0] & ~reg_be))) |
               (racl_addr_hit_write[1] & (|(I3C_PERMIT[1] & ~reg_be))) |
               (racl_addr_hit_write[2] & (|(I3C_PERMIT[2] & ~reg_be))) |
               (racl_addr_hit_write[3] & (|(I3C_PERMIT[3] & ~reg_be))) |
               (racl_addr_hit_write[4] & (|(I3C_PERMIT[4] & ~reg_be))) |
               (racl_addr_hit_write[5] & (|(I3C_PERMIT[5] & ~reg_be))) |
               (racl_addr_hit_write[6] & (|(I3C_PERMIT[6] & ~reg_be))) |
               (racl_addr_hit_write[7] & (|(I3C_PERMIT[7] & ~reg_be)))));
  end

  // Generate write-enables
  assign intr_enable_we = racl_addr_hit_write[1] & reg_we & !reg_error;

  assign intr_enable_wd = reg_wdata[0];
  assign intr_test_we = racl_addr_hit_write[2] & reg_we & !reg_error;

  assign intr_test_wd = reg_wdata[0];
  assign alert_test_we = racl_addr_hit_write[3] & reg_we & !reg_error;

  assign alert_test_wd = reg_wdata[0];
  assign ctrl_we = racl_addr_hit_write[4] & reg_we & !reg_error;

  assign ctrl_ctrl_en_wd = reg_wdata[0];

  assign ctrl_targ_en_wd = reg_wdata[1];

  assign ctrl_clkdiv_wd = reg_wdata[31:16];
  assign status_re = racl_addr_hit_read[5] & reg_re & !reg_error;
  assign buffer_config_we = racl_addr_hit_write[6] & reg_we & !reg_error;

  assign buffer_config_ctrl_tx_size_wd = reg_wdata[7:0];

  assign buffer_config_ctrl_rx_size_wd = reg_wdata[15:8];

  assign buffer_config_targ_tx_size_wd = reg_wdata[23:16];

  assign buffer_config_targ_rx_size_wd = reg_wdata[31:24];
  assign buffer_status_re = racl_addr_hit_read[7] & reg_re & !reg_error;

  // Assign write-enables to checker logic vector.
  always_comb begin
    reg_we_check[0] = 1'b0;
    reg_we_check[1] = intr_enable_we;
    reg_we_check[2] = intr_test_we;
    reg_we_check[3] = alert_test_we;
    reg_we_check[4] = ctrl_we;
    reg_we_check[5] = 1'b0;
    reg_we_check[6] = buffer_config_we;
    reg_we_check[7] = 1'b0;
  end

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      racl_addr_hit_read[0]: begin
        reg_rdata_next[0] = intr_state_qs;
      end

      racl_addr_hit_read[1]: begin
        reg_rdata_next[0] = intr_enable_qs;
      end

      racl_addr_hit_read[2]: begin
        reg_rdata_next[0] = '0;
      end

      racl_addr_hit_read[3]: begin
        reg_rdata_next[0] = '0;
      end

      racl_addr_hit_read[4]: begin
        reg_rdata_next[0] = ctrl_ctrl_en_qs;
        reg_rdata_next[1] = ctrl_targ_en_qs;
        reg_rdata_next[31:16] = ctrl_clkdiv_qs;
      end

      racl_addr_hit_read[5]: begin
        reg_rdata_next[0] = status_tx_idle_qs;
        reg_rdata_next[1] = status_rx_idle_qs;
      end

      racl_addr_hit_read[6]: begin
        reg_rdata_next[7:0] = buffer_config_ctrl_tx_size_qs;
        reg_rdata_next[15:8] = buffer_config_ctrl_rx_size_qs;
        reg_rdata_next[23:16] = buffer_config_targ_tx_size_qs;
        reg_rdata_next[31:24] = buffer_config_targ_rx_size_qs;
      end

      racl_addr_hit_read[7]: begin
        reg_rdata_next[7:0] = buffer_status_txlvl_qs;
        reg_rdata_next[23:16] = buffer_status_rxlvl_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // shadow busy
  logic shadow_busy;
  assign shadow_busy = 1'b0;

  // register busy
  assign reg_busy = shadow_busy;

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;
  logic unused_policy_sel;
  assign unused_policy_sel = ^racl_policies_i;

  // Assertions for Register Interface
  `ASSERT_PULSE(wePulse, reg_we, clk_i, !rst_ni)
  `ASSERT_PULSE(rePulse, reg_re, clk_i, !rst_ni)

  `ASSERT(reAfterRv, $rose(reg_re || reg_we) |=> tl_o_pre.d_valid, clk_i, !rst_ni)

  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit), clk_i, !rst_ni)

  // this is formulated as an assumption such that the FPV testbenches do disprove this
  // property by mistake
  //`ASSUME(reqParity, tl_reg_h2d.a_valid |-> tl_reg_h2d.a_user.chk_en == tlul_pkg::CheckDis)

endmodule
