// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package i3c_reg_pkg;

  // Param list
  parameter int NumDATWords = 64;
  parameter int NumDCTWords = 128;
  parameter int NumAlerts = 1;

  // Address widths within the block
  parameter int BlockAw = 12;

  // Number of registers for every interface
  parameter int NumRegs = 73;

  // Alert indices
  typedef enum int {
    AlertFatalFaultIdx = 0
  } i3c_alert_idx_t;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    logic        q;
  } i3c_reg2hw_intr_state_reg_t;

  typedef struct packed {
    logic        q;
  } i3c_reg2hw_intr_enable_reg_t;

  typedef struct packed {
    logic        q;
    logic        qe;
  } i3c_reg2hw_intr_test_reg_t;

  typedef struct packed {
    logic        q;
    logic        qe;
  } i3c_reg2hw_alert_test_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } targ_reset;
    struct packed {
      logic        q;
      logic        qe;
    } ctrl_reset;
    struct packed {
      logic        q;
    } hdr_ddr_en;
    struct packed {
      logic        q;
    } targ_rx_en;
    struct packed {
      logic        q;
    } targ_tx_en;
    struct packed {
      logic        q;
    } ctrl_rx_en;
    struct packed {
      logic        q;
    } ctrl_tx_en;
  } i3c_reg2hw_ctrl_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } sda_hk_en;
    struct packed {
      logic        q;
    } scl_hk_en;
  } i3c_reg2hw_phy_config_reg_t;

  typedef struct packed {
    struct packed {
      logic [2:0]  q;
    } size_val;
    struct packed {
      logic [9:0] q;
    } max_addr;
    struct packed {
      logic [9:0] q;
    } min_addr;
  } i3c_reg2hw_ctrl_txbuf_config_reg_t;

  typedef struct packed {
    logic [15:0] q;
  } i3c_reg2hw_ctrl_txbuf_wptr_reg_t;

  typedef struct packed {
    logic [15:0] q;
  } i3c_reg2hw_ctrl_txbuf_rptr_reg_t;

  typedef struct packed {
    struct packed {
      logic [2:0]  q;
    } size_val;
    struct packed {
      logic [9:0] q;
    } max_addr;
    struct packed {
      logic [9:0] q;
    } min_addr;
  } i3c_reg2hw_ctrl_rxbuf_config_reg_t;

  typedef struct packed {
    logic [15:0] q;
  } i3c_reg2hw_ctrl_rxbuf_wptr_reg_t;

  typedef struct packed {
    logic [15:0] q;
  } i3c_reg2hw_ctrl_rxbuf_rptr_reg_t;

  typedef struct packed {
    struct packed {
      logic [9:0] q;
    } max_addr;
    struct packed {
      logic [9:0] q;
    } min_addr;
  } i3c_reg2hw_targ_txbuf_config_reg_t;

  typedef struct packed {
    logic [15:0] q;
  } i3c_reg2hw_targ_txbuf_wptr_reg_t;

  typedef struct packed {
    logic [15:0] q;
  } i3c_reg2hw_targ_txbuf_rptr_reg_t;

  typedef struct packed {
    struct packed {
      logic [9:0] q;
    } max_addr;
    struct packed {
      logic [9:0] q;
    } min_addr;
  } i3c_reg2hw_targ_rxbuf_config_reg_t;

  typedef struct packed {
    logic [15:0] q;
  } i3c_reg2hw_targ_rxbuf_wptr_reg_t;

  typedef struct packed {
    logic [15:0] q;
  } i3c_reg2hw_targ_rxbuf_rptr_reg_t;

  typedef struct packed {
    logic        q;
    logic        qe;
  } i3c_reg2hw_buffer_ctrl_reg_t;

  typedef struct packed {
    struct packed {
      logic [6:0]  q;
    } addr1;
    struct packed {
      logic [6:0]  q;
    } addr0;
  } i3c_reg2hw_targ_addr_match_reg_t;

  typedef struct packed {
    struct packed {
      logic [6:0]  q;
    } mask1;
    struct packed {
      logic [6:0]  q;
    } mask0;
  } i3c_reg2hw_targ_addr_mask_reg_t;

  typedef struct packed {
    struct packed {
      logic [15:0] q;
    } clkdiv;
    struct packed {
      logic [7:0]  q;
    } tcas;
    struct packed {
      logic [7:0]  q;
    } tcbp;
  } i3c_reg2hw_ctrl_clk_config_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } bus_enable;
    struct packed {
      logic        q;
    } resume;
    struct packed {
      logic        q;
    } abort;
    struct packed {
      logic        q;
    } halt_on_cmd_seq_timeout;
    struct packed {
      logic        q;
    } hot_join_ctrl;
    struct packed {
      logic        q;
    } i2c_dev_present;
    struct packed {
      logic        q;
    } autocmd_data_rpt;
    struct packed {
      logic        q;
    } iba_include;
  } i3c_reg2hw_hc_control_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } dynamic_addr_valid;
    struct packed {
      logic [6:0]  q;
    } dynamic_addr;
  } i3c_reg2hw_controller_device_addr_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } ibi_queue_rst;
    struct packed {
      logic        q;
    } rx_fifo_rst;
    struct packed {
      logic        q;
    } tx_fifo_rst;
    struct packed {
      logic        q;
    } resp_queue_rst;
    struct packed {
      logic        q;
    } cmd_queue_rst;
    struct packed {
      logic        q;
    } soft_rst;
  } i3c_reg2hw_reset_control_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } sched_cmd_missed_tick_stat;
    struct packed {
      logic        q;
    } hc_err_cmd_seq_timeout_stat;
    struct packed {
      logic        q;
    } hc_warn_cmd_seq_stall_stat;
    struct packed {
      logic        q;
    } hc_seq_cancel_stat;
    struct packed {
      logic        q;
    } hc_internal_err_stat;
  } i3c_reg2hw_intr_status_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } sched_cmd_missed_tick_stat_en;
    struct packed {
      logic        q;
    } hc_err_cmd_seq_timeout_stat_en;
    struct packed {
      logic        q;
    } hc_warn_cmd_seq_stall_stat_en;
    struct packed {
      logic        q;
    } hc_seq_cancel_stat_en;
    struct packed {
      logic        q;
    } hc_internal_err_stat_en;
  } i3c_reg2hw_intr_status_enable_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } sched_cmd_missed_tick_signal_en;
    struct packed {
      logic        q;
    } hc_err_cmd_seq_timeout_signal_en;
    struct packed {
      logic        q;
    } hc_warn_cmd_seq_stall_signal_en;
    struct packed {
      logic        q;
    } hc_seq_cancel_signal_en;
    struct packed {
      logic        q;
    } hc_internal_err_signal_en;
  } i3c_reg2hw_intr_signal_enable_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } sched_cmd_missed_tick_force;
    struct packed {
      logic        q;
      logic        qe;
    } hc_err_cmd_seq_timeout_force;
    struct packed {
      logic        q;
      logic        qe;
    } hc_warn_cmd_seq_stall_force;
    struct packed {
      logic        q;
      logic        qe;
    } hc_seq_cancel_force;
    struct packed {
      logic        q;
      logic        qe;
    } hc_internal_err_force;
  } i3c_reg2hw_intr_force_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } notify_ibi_rejected;
    struct packed {
      logic        q;
    } notify_crr_rejected;
    struct packed {
      logic        q;
    } notify_hj_rejected;
  } i3c_reg2hw_ibi_notify_ctrl_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } ibi_data_abort_mon;
    struct packed {
      logic [2:0]  q;
    } match_status_type;
    struct packed {
      logic [1:0]  q;
    } after_n_chunks;
    struct packed {
      logic [7:0]  q;
    } match_ibi_id;
  } i3c_reg2hw_ibi_data_abort_ctrl_reg_t;

  typedef struct packed {
    logic [31:0] q;
    logic        qe;
  } i3c_reg2hw_command_queue_port_reg_t;

  typedef struct packed {
    logic [31:0] q;
    logic        re;
  } i3c_reg2hw_response_queue_port_reg_t;

  typedef struct packed {
    logic [31:0] q;
    logic        qe;
    logic        re;
  } i3c_reg2hw_ibi_port_reg_t;

  typedef struct packed {
    struct packed {
      logic [7:0]  q;
    } ibi_status_thld;
    struct packed {
      logic [7:0]  q;
    } ibi_data_segment_size;
    struct packed {
      logic [7:0]  q;
    } resp_buf_thld;
    struct packed {
      logic [7:0]  q;
    } cmd_empty_buf_thld;
  } i3c_reg2hw_queue_thld_ctrl_reg_t;

  typedef struct packed {
    struct packed {
      logic [2:0]  q;
    } rx_start_thld;
    struct packed {
      logic [2:0]  q;
    } tx_start_thld;
    struct packed {
      logic [2:0]  q;
    } rx_buf_thld;
    struct packed {
      logic [2:0]  q;
    } tx_buf_thld;
  } i3c_reg2hw_data_buffer_thld_ctrl_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } transfer_err_stat;
    struct packed {
      logic        q;
    } transfer_abort_stat;
    struct packed {
      logic        q;
    } resp_ready_stat;
    struct packed {
      logic        q;
    } cmd_queue_ready_stat;
    struct packed {
      logic        q;
    } ibi_status_thld_stat;
    struct packed {
      logic        q;
    } rx_thld_stat;
    struct packed {
      logic        q;
    } tx_thld_stat;
  } i3c_reg2hw_pio_intr_status_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } transfer_err_stat_en;
    struct packed {
      logic        q;
    } transfer_abort_stat_en;
    struct packed {
      logic        q;
    } resp_ready_stat_en;
    struct packed {
      logic        q;
    } cmd_queue_ready_stat_en;
    struct packed {
      logic        q;
    } ibi_status_thld_stat_en;
    struct packed {
      logic        q;
    } rx_thld_stat_en;
    struct packed {
      logic        q;
    } tx_thld_stat_en;
  } i3c_reg2hw_pio_intr_status_enable_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } transfer_err_signal_en;
    struct packed {
      logic        q;
    } transfer_abort_signal_en;
    struct packed {
      logic        q;
    } resp_ready_signal_en;
    struct packed {
      logic        q;
    } cmd_queue_ready_signal_en;
    struct packed {
      logic        q;
    } ibi_status_thld_signal_en;
    struct packed {
      logic        q;
    } rx_thld_signal_en;
    struct packed {
      logic        q;
    } tx_thld_signal_en;
  } i3c_reg2hw_pio_intr_signal_enable_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } transfer_err_force;
    struct packed {
      logic        q;
    } transfer_abort_force;
    struct packed {
      logic        q;
    } resp_ready_force;
    struct packed {
      logic        q;
    } cmd_queue_ready_force;
    struct packed {
      logic        q;
    } ibi_thld_force;
    struct packed {
      logic        q;
    } rx_thld_force;
    struct packed {
      logic        q;
    } tx_thld_force;
  } i3c_reg2hw_pio_intr_force_reg_t;

  typedef struct packed {
    struct packed {
      logic [1:0]  q;
    } stby_cr_enable_init;
    struct packed {
      logic        q;
    } rstact_defbyte_02;
    struct packed {
      logic        q;
    } daa_entdaa_enable;
    struct packed {
      logic        q;
    } daa_setdasa_enable;
    struct packed {
      logic        q;
    } daa_setaasa_enable;
    struct packed {
      logic        q;
    } target_xact_enable;
    struct packed {
      logic [2:0]  q;
    } bcast_ccc_ibi_ring;
    struct packed {
      logic        q;
    } cr_request_send;
    struct packed {
      logic        q;
    } handoff_deep_sleep;
    struct packed {
      logic        q;
    } prime_accept_getaccr;
    struct packed {
      logic        q;
    } acr_fsm_op_select;
    struct packed {
      logic        q;
    } handoff_delay_nack;
    struct packed {
      logic        q;
    } pending_rx_nack;
  } i3c_reg2hw_stby_cr_control_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } dynamic_addr_valid;
    struct packed {
      logic [6:0]  q;
    } dynamic_addr;
    struct packed {
      logic        q;
    } static_addr_valid;
    struct packed {
      logic [6:0]  q;
    } static_addr;
  } i3c_reg2hw_stby_cr_device_addr_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } hj_req_status;
    struct packed {
      logic [2:0]  q;
    } simple_crr_status;
    struct packed {
      logic        q;
    } ac_current_own;
  } i3c_reg2hw_stby_cr_status_reg_t;

  typedef struct packed {
    struct packed {
      logic [2:0]  q;
    } bcr_fixed;
    struct packed {
      logic [4:0]  q;
    } bcr_var;
    struct packed {
      logic [7:0]  q;
    } dcr;
    struct packed {
      logic [14:0] q;
    } pid_hi;
  } i3c_reg2hw_stby_cr_device_char_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } i3c_reg2hw_stby_cr_device_pid_lo_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } ccc_fatal_rstdaa_err_stat;
    struct packed {
      logic        q;
    } ccc_unhandled_nack_stat;
    struct packed {
      logic        q;
    } ccc_param_modified_stat;
    struct packed {
      logic        q;
    } stby_cr_op_rstact_stat;
    struct packed {
      logic        q;
    } stby_cr_accept_err_stat;
    struct packed {
      logic        q;
    } stby_cr_accept_ok_stat;
    struct packed {
      logic        q;
    } stby_cr_accept_nacked_stat;
    struct packed {
      logic        q;
    } stby_cr_dyn_addr_stat;
    struct packed {
      logic        q;
    } crr_response_stat;
    struct packed {
      logic        q;
    } acr_handoff_err_m3_stat;
    struct packed {
      logic        q;
    } acr_handoff_err_fail_stat;
    struct packed {
      logic        q;
    } acr_handoff_ok_primed_stat;
    struct packed {
      logic        q;
    } acr_handoff_ok_remain_stat;
  } i3c_reg2hw_stby_cr_intr_status_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } ccc_fatal_rstdaa_err_signal_en;
    struct packed {
      logic        q;
    } ccc_unhandled_nack_signal_en;
    struct packed {
      logic        q;
    } ccc_param_modified_signal_en;
    struct packed {
      logic        q;
    } stby_cr_op_rstact_signal_en;
    struct packed {
      logic        q;
    } stby_cr_accept_err_signal_en;
    struct packed {
      logic        q;
    } stby_cr_accept_ok_signal_en;
    struct packed {
      logic        q;
    } stby_cr_accept_nacked_signal_en;
    struct packed {
      logic        q;
    } stby_cr_dyn_addr_signal_en;
    struct packed {
      logic        q;
    } crr_response_signal_en;
    struct packed {
      logic        q;
    } acr_handoff_err_m3_signal_en;
    struct packed {
      logic        q;
    } acr_handoff_err_fail_signal_en;
    struct packed {
      logic        q;
    } acr_handoff_ok_primed_signal_en;
    struct packed {
      logic        q;
    } acr_handoff_ok_remain_signal_en;
  } i3c_reg2hw_stby_cr_intr_signal_enable_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } ccc_fatal_rstdaa_err_force;
    struct packed {
      logic        q;
    } ccc_unhandled_nack_force;
    struct packed {
      logic        q;
    } ccc_param_modified_force;
    struct packed {
      logic        q;
    } stby_cr_op_rstact_force;
    struct packed {
      logic        q;
    } stby_cr_accept_err_force;
    struct packed {
      logic        q;
    } stby_cr_accept_ok_force;
    struct packed {
      logic        q;
    } stby_cr_accept_nacked_force;
    struct packed {
      logic        q;
    } stby_cr_dyn_addr_force;
    struct packed {
      logic        q;
    } crr_response_force;
  } i3c_reg2hw_stby_cr_intr_force_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } reset_dynamic_addr;
    struct packed {
      logic [7:0]  q;
    } reset_time_target;
    struct packed {
      logic [7:0]  q;
    } reset_time_peripheral;
    struct packed {
      logic [7:0]  q;
    } rst_action;
  } i3c_reg2hw_stby_cr_ccc_config_rstact_params_reg_t;

  typedef struct packed {
    logic        d;
    logic        de;
  } i3c_hw2reg_intr_state_reg_t;

  typedef struct packed {
    logic        d;
  } i3c_hw2reg_status_reg_t;

  typedef struct packed {
    logic [15:0] d;
    logic        de;
  } i3c_hw2reg_ctrl_txbuf_wptr_reg_t;

  typedef struct packed {
    logic [15:0] d;
    logic        de;
  } i3c_hw2reg_ctrl_txbuf_rptr_reg_t;

  typedef struct packed {
    logic [15:0] d;
    logic        de;
  } i3c_hw2reg_ctrl_rxbuf_wptr_reg_t;

  typedef struct packed {
    logic [15:0] d;
    logic        de;
  } i3c_hw2reg_ctrl_rxbuf_rptr_reg_t;

  typedef struct packed {
    logic [15:0] d;
    logic        de;
  } i3c_hw2reg_targ_txbuf_rptr_reg_t;

  typedef struct packed {
    logic [15:0] d;
    logic        de;
  } i3c_hw2reg_targ_rxbuf_wptr_reg_t;

  typedef struct packed {
    logic [31:0] d;
  } i3c_hw2reg_hci_version_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } mode_selector;
    struct packed {
      logic        d;
      logic        de;
    } data_byte_order_mode;
  } i3c_hw2reg_hc_control_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
    } sg_capability_dc_en;
    struct packed {
      logic        d;
    } sg_capability_ibi_en;
    struct packed {
      logic        d;
    } sg_capability_cr_en;
    struct packed {
      logic [1:0]  d;
    } cmd_size;
    struct packed {
      logic        d;
    } schedule_commands_en;
    struct packed {
      logic        d;
    } ibi_credit_count_en;
    struct packed {
      logic        d;
    } ibi_data_abort_en;
    struct packed {
      logic        d;
    } cmd_ccc_defbyte;
    struct packed {
      logic        d;
    } hdr_ts_en;
    struct packed {
      logic        d;
    } hdr_ddr_en;
    struct packed {
      logic        d;
    } standby_cr_cap;
    struct packed {
      logic        d;
    } auto_command;
    struct packed {
      logic        d;
    } combo_command;
  } i3c_hw2reg_hc_capabilities_reg_t;

  typedef struct packed {
    logic        d;
  } i3c_hw2reg_present_state_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } sched_cmd_missed_tick_stat;
    struct packed {
      logic        d;
      logic        de;
    } hc_err_cmd_seq_timeout_stat;
    struct packed {
      logic        d;
      logic        de;
    } hc_warn_cmd_seq_stall_stat;
    struct packed {
      logic        d;
      logic        de;
    } hc_seq_cancel_stat;
    struct packed {
      logic        d;
      logic        de;
    } hc_internal_err_stat;
  } i3c_hw2reg_intr_status_reg_t;

  typedef struct packed {
    struct packed {
      logic [3:0]  d;
    } entry_size;
    struct packed {
      logic [6:0]  d;
    } table_size;
    struct packed {
      logic [11:0] d;
    } table_offset;
  } i3c_hw2reg_dat_section_offset_reg_t;

  typedef struct packed {
    struct packed {
      logic [3:0]  d;
    } entry_size;
    struct packed {
      logic [6:0]  d;
    } table_size;
    struct packed {
      logic [11:0] d;
    } table_offset;
  } i3c_hw2reg_dct_section_offset_reg_t;

  typedef struct packed {
    logic [15:0] d;
  } i3c_hw2reg_ring_headers_section_offset_reg_t;

  typedef struct packed {
    logic [15:0] d;
  } i3c_hw2reg_pio_section_offset_reg_t;

  typedef struct packed {
    logic [15:0] d;
  } i3c_hw2reg_ext_caps_section_offset_reg_t;

  typedef struct packed {
    struct packed {
      logic [14:0] d;
    } mipi_cmds_supported;
    struct packed {
      logic        d;
    } icc_support;
  } i3c_hw2reg_int_ctrl_cmds_en_reg_t;

  typedef struct packed {
    logic [31:0] d;
  } i3c_hw2reg_dev_ctx_base_lo_reg_t;

  typedef struct packed {
    logic [31:0] d;
  } i3c_hw2reg_dev_ctx_base_hi_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
    } blp;
    struct packed {
      logic [15:0] d;
    } list_size;
  } i3c_hw2reg_dev_ctx_sg_reg_t;

  typedef struct packed {
    logic [31:0] d;
  } i3c_hw2reg_response_queue_port_reg_t;

  typedef struct packed {
    logic [31:0] d;
  } i3c_hw2reg_ibi_port_reg_t;

  typedef struct packed {
    struct packed {
      logic [7:0]  d;
    } tx_data_buffer_size;
    struct packed {
      logic [7:0]  d;
    } rx_data_buffer_size;
    struct packed {
      logic [7:0]  d;
    } ibi_status_size;
    struct packed {
      logic [7:0]  d;
    } cr_queue_size;
  } i3c_hw2reg_queue_size_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
    } ext_ibi_queue_en;
    struct packed {
      logic        d;
    } alt_resp_queue_en;
    struct packed {
      logic [7:0]  d;
    } alt_resp_queue_size;
  } i3c_hw2reg_alt_queue_size_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } transfer_err_stat;
    struct packed {
      logic        d;
      logic        de;
    } transfer_abort_stat;
    struct packed {
      logic        d;
      logic        de;
    } resp_ready_stat;
    struct packed {
      logic        d;
      logic        de;
    } cmd_queue_ready_stat;
    struct packed {
      logic        d;
      logic        de;
    } ibi_status_thld_stat;
    struct packed {
      logic        d;
      logic        de;
    } rx_thld_stat;
    struct packed {
      logic        d;
      logic        de;
    } tx_thld_stat;
  } i3c_hw2reg_pio_intr_status_reg_t;

  typedef struct packed {
    struct packed {
      logic [15:0] d;
    } cap_length;
    struct packed {
      logic [7:0]  d;
    } cap_id;
  } i3c_hw2reg_stby_extcap_header_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
    } daa_entdaa_support;
    struct packed {
      logic        d;
    } daa_setdasa_support;
    struct packed {
      logic        d;
    } daa_setaasa_support;
    struct packed {
      logic        d;
    } target_xact_support;
    struct packed {
      logic        d;
    } simple_crr_support;
  } i3c_hw2reg_stby_cr_capabilities_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } ccc_fatal_rstdaa_err_stat;
    struct packed {
      logic        d;
      logic        de;
    } ccc_unhandled_nack_stat;
    struct packed {
      logic        d;
      logic        de;
    } ccc_param_modified_stat;
    struct packed {
      logic        d;
      logic        de;
    } stby_cr_op_rstact_stat;
    struct packed {
      logic        d;
      logic        de;
    } stby_cr_accept_err_stat;
    struct packed {
      logic        d;
      logic        de;
    } stby_cr_accept_ok_stat;
    struct packed {
      logic        d;
      logic        de;
    } stby_cr_accept_nacked_stat;
    struct packed {
      logic        d;
      logic        de;
    } stby_cr_dyn_addr_stat;
    struct packed {
      logic        d;
      logic        de;
    } crr_response_stat;
    struct packed {
      logic        d;
      logic        de;
    } acr_handoff_err_m3_stat;
    struct packed {
      logic        d;
      logic        de;
    } acr_handoff_err_fail_stat;
    struct packed {
      logic        d;
      logic        de;
    } acr_handoff_ok_primed_stat;
    struct packed {
      logic        d;
      logic        de;
    } acr_handoff_ok_remain_stat;
  } i3c_hw2reg_stby_cr_intr_status_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
    } f2_crcap2_dev_interact;
    struct packed {
      logic [2:0]  d;
    } f2_crcap1_bus_config;
  } i3c_hw2reg_stby_cr_ccc_config_getcaps_reg_t;

  typedef struct packed {
    struct packed {
      logic [15:0] d;
    } cap_length;
    struct packed {
      logic [7:0]  d;
    } cap_id;
  } i3c_hw2reg_debug_extcap_header_reg_t;

  typedef struct packed {
    struct packed {
      logic [4:0]  d;
    } ibi_status_cnt;
    struct packed {
      logic [7:0]  d;
    } ibi_buffer_lvl;
    struct packed {
      logic [7:0]  d;
    } response_buffer_lvl;
    struct packed {
      logic [7:0]  d;
    } cmd_queue_free_lvl;
  } i3c_hw2reg_queue_status_level_reg_t;

  typedef struct packed {
    struct packed {
      logic [7:0]  d;
    } rx_buf_lvl;
    struct packed {
      logic [7:0]  d;
    } tx_buf_free_lvl;
  } i3c_hw2reg_data_buffer_status_level_reg_t;

  typedef struct packed {
    struct packed {
      logic [3:0]  d;
    } cmd_tid;
    struct packed {
      logic [5:0]  d;
    } bcl_tfr_st_status;
    struct packed {
      logic [5:0]  d;
    } bcl_tfr_status;
    struct packed {
      logic        d;
    } sda_line_signal_level;
    struct packed {
      logic        d;
    } scl_line_signal_level;
  } i3c_hw2reg_present_state_debug_reg_t;

  typedef struct packed {
    logic [7:0]  d;
  } i3c_hw2reg_mx_error_counters_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
    } err_occurred;
    struct packed {
      logic [4:0]  d;
    } tick_interval;
    struct packed {
      logic [7:0]  d;
    } entity_id;
    struct packed {
      logic        d;
    } err_type;
    struct packed {
      logic [2:0]  d;
    } inst_id;
    struct packed {
      logic [3:0]  d;
    } sched_handler;
  } i3c_hw2reg_sched_cmds_debug_reg_t;

  // Register -> HW type
  typedef struct packed {
    i3c_reg2hw_intr_state_reg_t intr_state; // [688:688]
    i3c_reg2hw_intr_enable_reg_t intr_enable; // [687:687]
    i3c_reg2hw_intr_test_reg_t intr_test; // [686:685]
    i3c_reg2hw_alert_test_reg_t alert_test; // [684:683]
    i3c_reg2hw_ctrl_reg_t ctrl; // [682:674]
    i3c_reg2hw_phy_config_reg_t phy_config; // [673:672]
    i3c_reg2hw_ctrl_txbuf_config_reg_t ctrl_txbuf_config; // [671:649]
    i3c_reg2hw_ctrl_txbuf_wptr_reg_t ctrl_txbuf_wptr; // [648:633]
    i3c_reg2hw_ctrl_txbuf_rptr_reg_t ctrl_txbuf_rptr; // [632:617]
    i3c_reg2hw_ctrl_rxbuf_config_reg_t ctrl_rxbuf_config; // [616:594]
    i3c_reg2hw_ctrl_rxbuf_wptr_reg_t ctrl_rxbuf_wptr; // [593:578]
    i3c_reg2hw_ctrl_rxbuf_rptr_reg_t ctrl_rxbuf_rptr; // [577:562]
    i3c_reg2hw_targ_txbuf_config_reg_t targ_txbuf_config; // [561:542]
    i3c_reg2hw_targ_txbuf_wptr_reg_t targ_txbuf_wptr; // [541:526]
    i3c_reg2hw_targ_txbuf_rptr_reg_t targ_txbuf_rptr; // [525:510]
    i3c_reg2hw_targ_rxbuf_config_reg_t targ_rxbuf_config; // [509:490]
    i3c_reg2hw_targ_rxbuf_wptr_reg_t targ_rxbuf_wptr; // [489:474]
    i3c_reg2hw_targ_rxbuf_rptr_reg_t targ_rxbuf_rptr; // [473:458]
    i3c_reg2hw_buffer_ctrl_reg_t buffer_ctrl; // [457:456]
    i3c_reg2hw_targ_addr_match_reg_t targ_addr_match; // [455:442]
    i3c_reg2hw_targ_addr_mask_reg_t targ_addr_mask; // [441:428]
    i3c_reg2hw_ctrl_clk_config_reg_t ctrl_clk_config; // [427:396]
    i3c_reg2hw_hc_control_reg_t hc_control; // [395:388]
    i3c_reg2hw_controller_device_addr_reg_t controller_device_addr; // [387:380]
    i3c_reg2hw_reset_control_reg_t reset_control; // [379:374]
    i3c_reg2hw_intr_status_reg_t intr_status; // [373:369]
    i3c_reg2hw_intr_status_enable_reg_t intr_status_enable; // [368:364]
    i3c_reg2hw_intr_signal_enable_reg_t intr_signal_enable; // [363:359]
    i3c_reg2hw_intr_force_reg_t intr_force; // [358:349]
    i3c_reg2hw_ibi_notify_ctrl_reg_t ibi_notify_ctrl; // [348:346]
    i3c_reg2hw_ibi_data_abort_ctrl_reg_t ibi_data_abort_ctrl; // [345:332]
    i3c_reg2hw_command_queue_port_reg_t command_queue_port; // [331:299]
    i3c_reg2hw_response_queue_port_reg_t response_queue_port; // [298:266]
    i3c_reg2hw_ibi_port_reg_t ibi_port; // [265:232]
    i3c_reg2hw_queue_thld_ctrl_reg_t queue_thld_ctrl; // [231:200]
    i3c_reg2hw_data_buffer_thld_ctrl_reg_t data_buffer_thld_ctrl; // [199:188]
    i3c_reg2hw_pio_intr_status_reg_t pio_intr_status; // [187:181]
    i3c_reg2hw_pio_intr_status_enable_reg_t pio_intr_status_enable; // [180:174]
    i3c_reg2hw_pio_intr_signal_enable_reg_t pio_intr_signal_enable; // [173:167]
    i3c_reg2hw_pio_intr_force_reg_t pio_intr_force; // [166:160]
    i3c_reg2hw_stby_cr_control_reg_t stby_cr_control; // [159:144]
    i3c_reg2hw_stby_cr_device_addr_reg_t stby_cr_device_addr; // [143:128]
    i3c_reg2hw_stby_cr_status_reg_t stby_cr_status; // [127:123]
    i3c_reg2hw_stby_cr_device_char_reg_t stby_cr_device_char; // [122:92]
    i3c_reg2hw_stby_cr_device_pid_lo_reg_t stby_cr_device_pid_lo; // [91:60]
    i3c_reg2hw_stby_cr_intr_status_reg_t stby_cr_intr_status; // [59:47]
    i3c_reg2hw_stby_cr_intr_signal_enable_reg_t stby_cr_intr_signal_enable; // [46:34]
    i3c_reg2hw_stby_cr_intr_force_reg_t stby_cr_intr_force; // [33:25]
    i3c_reg2hw_stby_cr_ccc_config_rstact_params_reg_t stby_cr_ccc_config_rstact_params; // [24:0]
  } i3c_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    i3c_hw2reg_intr_state_reg_t intr_state; // [652:651]
    i3c_hw2reg_status_reg_t status; // [650:650]
    i3c_hw2reg_ctrl_txbuf_wptr_reg_t ctrl_txbuf_wptr; // [649:633]
    i3c_hw2reg_ctrl_txbuf_rptr_reg_t ctrl_txbuf_rptr; // [632:616]
    i3c_hw2reg_ctrl_rxbuf_wptr_reg_t ctrl_rxbuf_wptr; // [615:599]
    i3c_hw2reg_ctrl_rxbuf_rptr_reg_t ctrl_rxbuf_rptr; // [598:582]
    i3c_hw2reg_targ_txbuf_rptr_reg_t targ_txbuf_rptr; // [581:565]
    i3c_hw2reg_targ_rxbuf_wptr_reg_t targ_rxbuf_wptr; // [564:548]
    i3c_hw2reg_hci_version_reg_t hci_version; // [547:516]
    i3c_hw2reg_hc_control_reg_t hc_control; // [515:512]
    i3c_hw2reg_hc_capabilities_reg_t hc_capabilities; // [511:498]
    i3c_hw2reg_present_state_reg_t present_state; // [497:497]
    i3c_hw2reg_intr_status_reg_t intr_status; // [496:487]
    i3c_hw2reg_dat_section_offset_reg_t dat_section_offset; // [486:464]
    i3c_hw2reg_dct_section_offset_reg_t dct_section_offset; // [463:441]
    i3c_hw2reg_ring_headers_section_offset_reg_t ring_headers_section_offset; // [440:425]
    i3c_hw2reg_pio_section_offset_reg_t pio_section_offset; // [424:409]
    i3c_hw2reg_ext_caps_section_offset_reg_t ext_caps_section_offset; // [408:393]
    i3c_hw2reg_int_ctrl_cmds_en_reg_t int_ctrl_cmds_en; // [392:377]
    i3c_hw2reg_dev_ctx_base_lo_reg_t dev_ctx_base_lo; // [376:345]
    i3c_hw2reg_dev_ctx_base_hi_reg_t dev_ctx_base_hi; // [344:313]
    i3c_hw2reg_dev_ctx_sg_reg_t dev_ctx_sg; // [312:296]
    i3c_hw2reg_response_queue_port_reg_t response_queue_port; // [295:264]
    i3c_hw2reg_ibi_port_reg_t ibi_port; // [263:232]
    i3c_hw2reg_queue_size_reg_t queue_size; // [231:200]
    i3c_hw2reg_alt_queue_size_reg_t alt_queue_size; // [199:190]
    i3c_hw2reg_pio_intr_status_reg_t pio_intr_status; // [189:176]
    i3c_hw2reg_stby_extcap_header_reg_t stby_extcap_header; // [175:152]
    i3c_hw2reg_stby_cr_capabilities_reg_t stby_cr_capabilities; // [151:147]
    i3c_hw2reg_stby_cr_intr_status_reg_t stby_cr_intr_status; // [146:121]
    i3c_hw2reg_stby_cr_ccc_config_getcaps_reg_t stby_cr_ccc_config_getcaps; // [120:117]
    i3c_hw2reg_debug_extcap_header_reg_t debug_extcap_header; // [116:93]
    i3c_hw2reg_queue_status_level_reg_t queue_status_level; // [92:64]
    i3c_hw2reg_data_buffer_status_level_reg_t data_buffer_status_level; // [63:48]
    i3c_hw2reg_present_state_debug_reg_t present_state_debug; // [47:30]
    i3c_hw2reg_mx_error_counters_reg_t mx_error_counters; // [29:22]
    i3c_hw2reg_sched_cmds_debug_reg_t sched_cmds_debug; // [21:0]
  } i3c_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] I3C_INTR_STATE_OFFSET = 12'h 0;
  parameter logic [BlockAw-1:0] I3C_INTR_ENABLE_OFFSET = 12'h 4;
  parameter logic [BlockAw-1:0] I3C_INTR_TEST_OFFSET = 12'h 8;
  parameter logic [BlockAw-1:0] I3C_ALERT_TEST_OFFSET = 12'h c;
  parameter logic [BlockAw-1:0] I3C_CTRL_OFFSET = 12'h 10;
  parameter logic [BlockAw-1:0] I3C_STATUS_OFFSET = 12'h 14;
  parameter logic [BlockAw-1:0] I3C_PHY_CONFIG_OFFSET = 12'h 18;
  parameter logic [BlockAw-1:0] I3C_CTRL_TXBUF_CONFIG_OFFSET = 12'h 1c;
  parameter logic [BlockAw-1:0] I3C_CTRL_TXBUF_WPTR_OFFSET = 12'h 20;
  parameter logic [BlockAw-1:0] I3C_CTRL_TXBUF_RPTR_OFFSET = 12'h 24;
  parameter logic [BlockAw-1:0] I3C_CTRL_RXBUF_CONFIG_OFFSET = 12'h 28;
  parameter logic [BlockAw-1:0] I3C_CTRL_RXBUF_WPTR_OFFSET = 12'h 2c;
  parameter logic [BlockAw-1:0] I3C_CTRL_RXBUF_RPTR_OFFSET = 12'h 30;
  parameter logic [BlockAw-1:0] I3C_TARG_TXBUF_CONFIG_OFFSET = 12'h 34;
  parameter logic [BlockAw-1:0] I3C_TARG_TXBUF_WPTR_OFFSET = 12'h 38;
  parameter logic [BlockAw-1:0] I3C_TARG_TXBUF_RPTR_OFFSET = 12'h 3c;
  parameter logic [BlockAw-1:0] I3C_TARG_RXBUF_CONFIG_OFFSET = 12'h 40;
  parameter logic [BlockAw-1:0] I3C_TARG_RXBUF_WPTR_OFFSET = 12'h 44;
  parameter logic [BlockAw-1:0] I3C_TARG_RXBUF_RPTR_OFFSET = 12'h 48;
  parameter logic [BlockAw-1:0] I3C_BUFFER_CTRL_OFFSET = 12'h 4c;
  parameter logic [BlockAw-1:0] I3C_TARG_ADDR_MATCH_OFFSET = 12'h 50;
  parameter logic [BlockAw-1:0] I3C_TARG_ADDR_MASK_OFFSET = 12'h 54;
  parameter logic [BlockAw-1:0] I3C_CTRL_CLK_CONFIG_OFFSET = 12'h 58;
  parameter logic [BlockAw-1:0] I3C_HCI_VERSION_OFFSET = 12'h 100;
  parameter logic [BlockAw-1:0] I3C_HC_CONTROL_OFFSET = 12'h 104;
  parameter logic [BlockAw-1:0] I3C_CONTROLLER_DEVICE_ADDR_OFFSET = 12'h 108;
  parameter logic [BlockAw-1:0] I3C_HC_CAPABILITIES_OFFSET = 12'h 10c;
  parameter logic [BlockAw-1:0] I3C_RESET_CONTROL_OFFSET = 12'h 120;
  parameter logic [BlockAw-1:0] I3C_PRESENT_STATE_OFFSET = 12'h 124;
  parameter logic [BlockAw-1:0] I3C_INTR_STATUS_OFFSET = 12'h 128;
  parameter logic [BlockAw-1:0] I3C_INTR_STATUS_ENABLE_OFFSET = 12'h 12c;
  parameter logic [BlockAw-1:0] I3C_INTR_SIGNAL_ENABLE_OFFSET = 12'h 130;
  parameter logic [BlockAw-1:0] I3C_INTR_FORCE_OFFSET = 12'h 134;
  parameter logic [BlockAw-1:0] I3C_DAT_SECTION_OFFSET_OFFSET = 12'h 138;
  parameter logic [BlockAw-1:0] I3C_DCT_SECTION_OFFSET_OFFSET = 12'h 13c;
  parameter logic [BlockAw-1:0] I3C_RING_HEADERS_SECTION_OFFSET_OFFSET = 12'h 140;
  parameter logic [BlockAw-1:0] I3C_PIO_SECTION_OFFSET_OFFSET = 12'h 144;
  parameter logic [BlockAw-1:0] I3C_EXT_CAPS_SECTION_OFFSET_OFFSET = 12'h 148;
  parameter logic [BlockAw-1:0] I3C_INT_CTRL_CMDS_EN_OFFSET = 12'h 14c;
  parameter logic [BlockAw-1:0] I3C_IBI_NOTIFY_CTRL_OFFSET = 12'h 158;
  parameter logic [BlockAw-1:0] I3C_IBI_DATA_ABORT_CTRL_OFFSET = 12'h 15c;
  parameter logic [BlockAw-1:0] I3C_DEV_CTX_BASE_LO_OFFSET = 12'h 160;
  parameter logic [BlockAw-1:0] I3C_DEV_CTX_BASE_HI_OFFSET = 12'h 164;
  parameter logic [BlockAw-1:0] I3C_DEV_CTX_SG_OFFSET = 12'h 168;
  parameter logic [BlockAw-1:0] I3C_COMMAND_QUEUE_PORT_OFFSET = 12'h 200;
  parameter logic [BlockAw-1:0] I3C_RESPONSE_QUEUE_PORT_OFFSET = 12'h 204;
  parameter logic [BlockAw-1:0] I3C_IBI_PORT_OFFSET = 12'h 20c;
  parameter logic [BlockAw-1:0] I3C_QUEUE_THLD_CTRL_OFFSET = 12'h 210;
  parameter logic [BlockAw-1:0] I3C_DATA_BUFFER_THLD_CTRL_OFFSET = 12'h 214;
  parameter logic [BlockAw-1:0] I3C_QUEUE_SIZE_OFFSET = 12'h 218;
  parameter logic [BlockAw-1:0] I3C_ALT_QUEUE_SIZE_OFFSET = 12'h 21c;
  parameter logic [BlockAw-1:0] I3C_PIO_INTR_STATUS_OFFSET = 12'h 220;
  parameter logic [BlockAw-1:0] I3C_PIO_INTR_STATUS_ENABLE_OFFSET = 12'h 224;
  parameter logic [BlockAw-1:0] I3C_PIO_INTR_SIGNAL_ENABLE_OFFSET = 12'h 228;
  parameter logic [BlockAw-1:0] I3C_PIO_INTR_FORCE_OFFSET = 12'h 22c;
  parameter logic [BlockAw-1:0] I3C_STBY_EXTCAP_HEADER_OFFSET = 12'h 230;
  parameter logic [BlockAw-1:0] I3C_STBY_CR_CONTROL_OFFSET = 12'h 234;
  parameter logic [BlockAw-1:0] I3C_STBY_CR_DEVICE_ADDR_OFFSET = 12'h 238;
  parameter logic [BlockAw-1:0] I3C_STBY_CR_CAPABILITIES_OFFSET = 12'h 23c;
  parameter logic [BlockAw-1:0] I3C_STBY_CR_STATUS_OFFSET = 12'h 240;
  parameter logic [BlockAw-1:0] I3C_STBY_CR_DEVICE_CHAR_OFFSET = 12'h 244;
  parameter logic [BlockAw-1:0] I3C_STBY_CR_DEVICE_PID_LO_OFFSET = 12'h 248;
  parameter logic [BlockAw-1:0] I3C_STBY_CR_INTR_STATUS_OFFSET = 12'h 24c;
  parameter logic [BlockAw-1:0] I3C_STBY_CR_INTR_SIGNAL_ENABLE_OFFSET = 12'h 250;
  parameter logic [BlockAw-1:0] I3C_STBY_CR_INTR_FORCE_OFFSET = 12'h 254;
  parameter logic [BlockAw-1:0] I3C_STBY_CR_CCC_CONFIG_GETCAPS_OFFSET = 12'h 258;
  parameter logic [BlockAw-1:0] I3C_STBY_CR_CCC_CONFIG_RSTACT_PARAMS_OFFSET = 12'h 25c;
  parameter logic [BlockAw-1:0] I3C_DEBUG_EXTCAP_HEADER_OFFSET = 12'h 280;
  parameter logic [BlockAw-1:0] I3C_QUEUE_STATUS_LEVEL_OFFSET = 12'h 284;
  parameter logic [BlockAw-1:0] I3C_DATA_BUFFER_STATUS_LEVEL_OFFSET = 12'h 288;
  parameter logic [BlockAw-1:0] I3C_PRESENT_STATE_DEBUG_OFFSET = 12'h 28c;
  parameter logic [BlockAw-1:0] I3C_MX_ERROR_COUNTERS_OFFSET = 12'h 290;
  parameter logic [BlockAw-1:0] I3C_SCHED_CMDS_DEBUG_OFFSET = 12'h 294;

  // Reset values for hwext registers and their fields
  parameter logic [0:0] I3C_INTR_TEST_RESVAL = 1'h 0;
  parameter logic [0:0] I3C_INTR_TEST_HCI_RESVAL = 1'h 0;
  parameter logic [0:0] I3C_ALERT_TEST_RESVAL = 1'h 0;
  parameter logic [0:0] I3C_ALERT_TEST_FATAL_FAULT_RESVAL = 1'h 0;
  parameter logic [0:0] I3C_STATUS_RESVAL = 1'h 0;
  parameter logic [31:0] I3C_HCI_VERSION_RESVAL = 32'h 120;
  parameter logic [31:0] I3C_HCI_VERSION_VERSION_RESVAL = 32'h 120;
  parameter logic [30:0] I3C_HC_CAPABILITIES_RESVAL = 31'h 3c6c;
  parameter logic [0:0] I3C_HC_CAPABILITIES_COMBO_COMMAND_RESVAL = 1'h 1;
  parameter logic [0:0] I3C_HC_CAPABILITIES_AUTO_COMMAND_RESVAL = 1'h 1;
  parameter logic [0:0] I3C_HC_CAPABILITIES_STANDBY_CR_CAP_RESVAL = 1'h 1;
  parameter logic [0:0] I3C_HC_CAPABILITIES_HDR_DDR_EN_RESVAL = 1'h 1;
  parameter logic [0:0] I3C_HC_CAPABILITIES_HDR_TS_EN_RESVAL = 1'h 0;
  parameter logic [0:0] I3C_HC_CAPABILITIES_CMD_CCC_DEFBYTE_RESVAL = 1'h 1;
  parameter logic [0:0] I3C_HC_CAPABILITIES_IBI_DATA_ABORT_EN_RESVAL = 1'h 1;
  parameter logic [0:0] I3C_HC_CAPABILITIES_IBI_CREDIT_COUNT_EN_RESVAL = 1'h 1;
  parameter logic [0:0] I3C_HC_CAPABILITIES_SCHEDULE_COMMANDS_EN_RESVAL = 1'h 1;
  parameter logic [1:0] I3C_HC_CAPABILITIES_CMD_SIZE_RESVAL = 2'h 0;
  parameter logic [0:0] I3C_HC_CAPABILITIES_SG_CAPABILITY_CR_EN_RESVAL = 1'h 0;
  parameter logic [0:0] I3C_HC_CAPABILITIES_SG_CAPABILITY_IBI_EN_RESVAL = 1'h 0;
  parameter logic [0:0] I3C_HC_CAPABILITIES_SG_CAPABILITY_DC_EN_RESVAL = 1'h 0;
  parameter logic [2:0] I3C_PRESENT_STATE_RESVAL = 3'h 0;
  parameter logic [0:0] I3C_PRESENT_STATE_AC_CURRENT_OWN_RESVAL = 1'h 0;
  parameter logic [14:0] I3C_INTR_FORCE_RESVAL = 15'h 0;
  parameter logic [0:0] I3C_INTR_FORCE_HC_INTERNAL_ERR_FORCE_RESVAL = 1'h 0;
  parameter logic [0:0] I3C_INTR_FORCE_HC_SEQ_CANCEL_FORCE_RESVAL = 1'h 0;
  parameter logic [0:0] I3C_INTR_FORCE_HC_WARN_CMD_SEQ_STALL_FORCE_RESVAL = 1'h 0;
  parameter logic [0:0] I3C_INTR_FORCE_HC_ERR_CMD_SEQ_TIMEOUT_FORCE_RESVAL = 1'h 0;
  parameter logic [0:0] I3C_INTR_FORCE_SCHED_CMD_MISSED_TICK_FORCE_RESVAL = 1'h 0;
  parameter logic [31:0] I3C_DAT_SECTION_OFFSET_RESVAL = 32'h 20000;
  parameter logic [6:0] I3C_DAT_SECTION_OFFSET_TABLE_SIZE_RESVAL = 7'h 20;
  parameter logic [3:0] I3C_DAT_SECTION_OFFSET_ENTRY_SIZE_RESVAL = 4'h 0;
  parameter logic [31:0] I3C_DCT_SECTION_OFFSET_RESVAL = 32'h 20000;
  parameter logic [6:0] I3C_DCT_SECTION_OFFSET_TABLE_SIZE_RESVAL = 7'h 20;
  parameter logic [3:0] I3C_DCT_SECTION_OFFSET_ENTRY_SIZE_RESVAL = 4'h 0;
  parameter logic [15:0] I3C_RING_HEADERS_SECTION_OFFSET_RESVAL = 16'h 0;
  parameter logic [15:0] I3C_RING_HEADERS_SECTION_OFFSET_SECTION_OFFSET_RESVAL = 16'h 0;
  parameter logic [15:0] I3C_PIO_SECTION_OFFSET_RESVAL = 16'h 100;
  parameter logic [15:0] I3C_PIO_SECTION_OFFSET_SECTION_OFFSET_RESVAL = 16'h 100;
  parameter logic [15:0] I3C_EXT_CAPS_SECTION_OFFSET_RESVAL = 16'h 0;
  parameter logic [15:0] I3C_EXT_CAPS_SECTION_OFFSET_SECTION_OFFSET_RESVAL = 16'h 0;
  parameter logic [15:0] I3C_INT_CTRL_CMDS_EN_RESVAL = 16'h 31;
  parameter logic [0:0] I3C_INT_CTRL_CMDS_EN_ICC_SUPPORT_RESVAL = 1'h 1;
  parameter logic [14:0] I3C_INT_CTRL_CMDS_EN_MIPI_CMDS_SUPPORTED_RESVAL = 15'h 18;
  parameter logic [31:0] I3C_DEV_CTX_BASE_LO_RESVAL = 32'h 0;
  parameter logic [31:0] I3C_DEV_CTX_BASE_LO_BASE_LO_RESVAL = 32'h 0;
  parameter logic [31:0] I3C_DEV_CTX_BASE_HI_RESVAL = 32'h 0;
  parameter logic [31:0] I3C_DEV_CTX_BASE_HI_BASE_HI_RESVAL = 32'h 0;
  parameter logic [31:0] I3C_DEV_CTX_SG_RESVAL = 32'h 0;
  parameter logic [15:0] I3C_DEV_CTX_SG_LIST_SIZE_RESVAL = 16'h 0;
  parameter logic [0:0] I3C_DEV_CTX_SG_BLP_RESVAL = 1'h 0;
  parameter logic [31:0] I3C_COMMAND_QUEUE_PORT_RESVAL = 32'h 0;
  parameter logic [31:0] I3C_RESPONSE_QUEUE_PORT_RESVAL = 32'h 0;
  parameter logic [31:0] I3C_IBI_PORT_RESVAL = 32'h 0;
  parameter logic [31:0] I3C_QUEUE_SIZE_RESVAL = 32'h 6060808;
  parameter logic [7:0] I3C_QUEUE_SIZE_CR_QUEUE_SIZE_RESVAL = 8'h 8;
  parameter logic [7:0] I3C_QUEUE_SIZE_IBI_STATUS_SIZE_RESVAL = 8'h 8;
  parameter logic [7:0] I3C_QUEUE_SIZE_RX_DATA_BUFFER_SIZE_RESVAL = 8'h 6;
  parameter logic [7:0] I3C_QUEUE_SIZE_TX_DATA_BUFFER_SIZE_RESVAL = 8'h 6;
  parameter logic [28:0] I3C_ALT_QUEUE_SIZE_RESVAL = 29'h 0;
  parameter logic [7:0] I3C_ALT_QUEUE_SIZE_ALT_RESP_QUEUE_SIZE_RESVAL = 8'h 0;
  parameter logic [0:0] I3C_ALT_QUEUE_SIZE_ALT_RESP_QUEUE_EN_RESVAL = 1'h 0;
  parameter logic [0:0] I3C_ALT_QUEUE_SIZE_EXT_IBI_QUEUE_EN_RESVAL = 1'h 0;
  parameter logic [23:0] I3C_STBY_EXTCAP_HEADER_RESVAL = 24'h 12;
  parameter logic [7:0] I3C_STBY_EXTCAP_HEADER_CAP_ID_RESVAL = 8'h 12;
  parameter logic [15:0] I3C_STBY_EXTCAP_HEADER_CAP_LENGTH_RESVAL = 16'h 0;
  parameter logic [15:0] I3C_STBY_CR_CAPABILITIES_RESVAL = 16'h f020;
  parameter logic [0:0] I3C_STBY_CR_CAPABILITIES_SIMPLE_CRR_SUPPORT_RESVAL = 1'h 1;
  parameter logic [0:0] I3C_STBY_CR_CAPABILITIES_TARGET_XACT_SUPPORT_RESVAL = 1'h 1;
  parameter logic [0:0] I3C_STBY_CR_CAPABILITIES_DAA_SETAASA_SUPPORT_RESVAL = 1'h 1;
  parameter logic [0:0] I3C_STBY_CR_CAPABILITIES_DAA_SETDASA_SUPPORT_RESVAL = 1'h 1;
  parameter logic [0:0] I3C_STBY_CR_CAPABILITIES_DAA_ENTDAA_SUPPORT_RESVAL = 1'h 1;
  parameter logic [4:0] I3C_STBY_CR_CCC_CONFIG_GETCAPS_RESVAL = 5'h 0;
  parameter logic [2:0] I3C_STBY_CR_CCC_CONFIG_GETCAPS_F2_CRCAP1_BUS_CONFIG_RESVAL = 3'h 0;
  parameter logic [0:0] I3C_STBY_CR_CCC_CONFIG_GETCAPS_F2_CRCAP2_DEV_INTERACT_RESVAL = 1'h 0;
  parameter logic [23:0] I3C_DEBUG_EXTCAP_HEADER_RESVAL = 24'h 12;
  parameter logic [7:0] I3C_DEBUG_EXTCAP_HEADER_CAP_ID_RESVAL = 8'h 12;
  parameter logic [15:0] I3C_DEBUG_EXTCAP_HEADER_CAP_LENGTH_RESVAL = 16'h 0;
  parameter logic [28:0] I3C_QUEUE_STATUS_LEVEL_RESVAL = 29'h 8;
  parameter logic [7:0] I3C_QUEUE_STATUS_LEVEL_CMD_QUEUE_FREE_LVL_RESVAL = 8'h 8;
  parameter logic [7:0] I3C_QUEUE_STATUS_LEVEL_RESPONSE_BUFFER_LVL_RESVAL = 8'h 0;
  parameter logic [7:0] I3C_QUEUE_STATUS_LEVEL_IBI_BUFFER_LVL_RESVAL = 8'h 0;
  parameter logic [4:0] I3C_QUEUE_STATUS_LEVEL_IBI_STATUS_CNT_RESVAL = 5'h 0;
  parameter logic [15:0] I3C_DATA_BUFFER_STATUS_LEVEL_RESVAL = 16'h 80;
  parameter logic [7:0] I3C_DATA_BUFFER_STATUS_LEVEL_TX_BUF_FREE_LVL_RESVAL = 8'h 80;
  parameter logic [7:0] I3C_DATA_BUFFER_STATUS_LEVEL_RX_BUF_LVL_RESVAL = 8'h 0;
  parameter logic [27:0] I3C_PRESENT_STATE_DEBUG_RESVAL = 28'h 3;
  parameter logic [0:0] I3C_PRESENT_STATE_DEBUG_SCL_LINE_SIGNAL_LEVEL_RESVAL = 1'h 1;
  parameter logic [0:0] I3C_PRESENT_STATE_DEBUG_SDA_LINE_SIGNAL_LEVEL_RESVAL = 1'h 1;
  parameter logic [5:0] I3C_PRESENT_STATE_DEBUG_BCL_TFR_STATUS_RESVAL = 6'h 0;
  parameter logic [5:0] I3C_PRESENT_STATE_DEBUG_BCL_TFR_ST_STATUS_RESVAL = 6'h 0;
  parameter logic [3:0] I3C_PRESENT_STATE_DEBUG_CMD_TID_RESVAL = 4'h 0;
  parameter logic [7:0] I3C_MX_ERROR_COUNTERS_RESVAL = 8'h 0;
  parameter logic [7:0] I3C_MX_ERROR_COUNTERS_CE2_ERROR_COUNT_RESVAL = 8'h 0;
  parameter logic [21:0] I3C_SCHED_CMDS_DEBUG_RESVAL = 22'h 0;
  parameter logic [3:0] I3C_SCHED_CMDS_DEBUG_SCHED_HANDLER_RESVAL = 4'h 0;
  parameter logic [2:0] I3C_SCHED_CMDS_DEBUG_INST_ID_RESVAL = 3'h 0;
  parameter logic [0:0] I3C_SCHED_CMDS_DEBUG_ERR_TYPE_RESVAL = 1'h 0;
  parameter logic [7:0] I3C_SCHED_CMDS_DEBUG_ENTITY_ID_RESVAL = 8'h 0;
  parameter logic [4:0] I3C_SCHED_CMDS_DEBUG_TICK_INTERVAL_RESVAL = 5'h 0;
  parameter logic [0:0] I3C_SCHED_CMDS_DEBUG_ERR_OCCURRED_RESVAL = 1'h 0;

  // Window parameters
  parameter logic [BlockAw-1:0] I3C_XFER_DATA_PORT_OFFSET = 12'h 208;
  parameter int unsigned        I3C_XFER_DATA_PORT_SIZE   = 'h 4;
  parameter int unsigned        I3C_XFER_DATA_PORT_IDX    = 0;
  parameter logic [BlockAw-1:0] I3C_DAT_OFFSET = 12'h 300;
  parameter int unsigned        I3C_DAT_SIZE   = 'h 100;
  parameter int unsigned        I3C_DAT_IDX    = 1;
  parameter logic [BlockAw-1:0] I3C_DCT_OFFSET = 12'h 400;
  parameter int unsigned        I3C_DCT_SIZE   = 'h 200;
  parameter int unsigned        I3C_DCT_IDX    = 2;
  parameter logic [BlockAw-1:0] I3C_BUFFER_OFFSET = 12'h 800;
  parameter int unsigned        I3C_BUFFER_SIZE   = 'h 800;
  parameter int unsigned        I3C_BUFFER_IDX    = 3;

  // Register index
  typedef enum int {
    I3C_INTR_STATE,
    I3C_INTR_ENABLE,
    I3C_INTR_TEST,
    I3C_ALERT_TEST,
    I3C_CTRL,
    I3C_STATUS,
    I3C_PHY_CONFIG,
    I3C_CTRL_TXBUF_CONFIG,
    I3C_CTRL_TXBUF_WPTR,
    I3C_CTRL_TXBUF_RPTR,
    I3C_CTRL_RXBUF_CONFIG,
    I3C_CTRL_RXBUF_WPTR,
    I3C_CTRL_RXBUF_RPTR,
    I3C_TARG_TXBUF_CONFIG,
    I3C_TARG_TXBUF_WPTR,
    I3C_TARG_TXBUF_RPTR,
    I3C_TARG_RXBUF_CONFIG,
    I3C_TARG_RXBUF_WPTR,
    I3C_TARG_RXBUF_RPTR,
    I3C_BUFFER_CTRL,
    I3C_TARG_ADDR_MATCH,
    I3C_TARG_ADDR_MASK,
    I3C_CTRL_CLK_CONFIG,
    I3C_HCI_VERSION,
    I3C_HC_CONTROL,
    I3C_CONTROLLER_DEVICE_ADDR,
    I3C_HC_CAPABILITIES,
    I3C_RESET_CONTROL,
    I3C_PRESENT_STATE,
    I3C_INTR_STATUS,
    I3C_INTR_STATUS_ENABLE,
    I3C_INTR_SIGNAL_ENABLE,
    I3C_INTR_FORCE,
    I3C_DAT_SECTION_OFFSET,
    I3C_DCT_SECTION_OFFSET,
    I3C_RING_HEADERS_SECTION_OFFSET,
    I3C_PIO_SECTION_OFFSET,
    I3C_EXT_CAPS_SECTION_OFFSET,
    I3C_INT_CTRL_CMDS_EN,
    I3C_IBI_NOTIFY_CTRL,
    I3C_IBI_DATA_ABORT_CTRL,
    I3C_DEV_CTX_BASE_LO,
    I3C_DEV_CTX_BASE_HI,
    I3C_DEV_CTX_SG,
    I3C_COMMAND_QUEUE_PORT,
    I3C_RESPONSE_QUEUE_PORT,
    I3C_IBI_PORT,
    I3C_QUEUE_THLD_CTRL,
    I3C_DATA_BUFFER_THLD_CTRL,
    I3C_QUEUE_SIZE,
    I3C_ALT_QUEUE_SIZE,
    I3C_PIO_INTR_STATUS,
    I3C_PIO_INTR_STATUS_ENABLE,
    I3C_PIO_INTR_SIGNAL_ENABLE,
    I3C_PIO_INTR_FORCE,
    I3C_STBY_EXTCAP_HEADER,
    I3C_STBY_CR_CONTROL,
    I3C_STBY_CR_DEVICE_ADDR,
    I3C_STBY_CR_CAPABILITIES,
    I3C_STBY_CR_STATUS,
    I3C_STBY_CR_DEVICE_CHAR,
    I3C_STBY_CR_DEVICE_PID_LO,
    I3C_STBY_CR_INTR_STATUS,
    I3C_STBY_CR_INTR_SIGNAL_ENABLE,
    I3C_STBY_CR_INTR_FORCE,
    I3C_STBY_CR_CCC_CONFIG_GETCAPS,
    I3C_STBY_CR_CCC_CONFIG_RSTACT_PARAMS,
    I3C_DEBUG_EXTCAP_HEADER,
    I3C_QUEUE_STATUS_LEVEL,
    I3C_DATA_BUFFER_STATUS_LEVEL,
    I3C_PRESENT_STATE_DEBUG,
    I3C_MX_ERROR_COUNTERS,
    I3C_SCHED_CMDS_DEBUG
  } i3c_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] I3C_PERMIT [73] = '{
    4'b 0001, // index[ 0] I3C_INTR_STATE
    4'b 0001, // index[ 1] I3C_INTR_ENABLE
    4'b 0001, // index[ 2] I3C_INTR_TEST
    4'b 0001, // index[ 3] I3C_ALERT_TEST
    4'b 1111, // index[ 4] I3C_CTRL
    4'b 0001, // index[ 5] I3C_STATUS
    4'b 0001, // index[ 6] I3C_PHY_CONFIG
    4'b 1111, // index[ 7] I3C_CTRL_TXBUF_CONFIG
    4'b 0011, // index[ 8] I3C_CTRL_TXBUF_WPTR
    4'b 0011, // index[ 9] I3C_CTRL_TXBUF_RPTR
    4'b 1111, // index[10] I3C_CTRL_RXBUF_CONFIG
    4'b 0011, // index[11] I3C_CTRL_RXBUF_WPTR
    4'b 0011, // index[12] I3C_CTRL_RXBUF_RPTR
    4'b 1111, // index[13] I3C_TARG_TXBUF_CONFIG
    4'b 0011, // index[14] I3C_TARG_TXBUF_WPTR
    4'b 0011, // index[15] I3C_TARG_TXBUF_RPTR
    4'b 1111, // index[16] I3C_TARG_RXBUF_CONFIG
    4'b 0011, // index[17] I3C_TARG_RXBUF_WPTR
    4'b 0011, // index[18] I3C_TARG_RXBUF_RPTR
    4'b 1111, // index[19] I3C_BUFFER_CTRL
    4'b 0011, // index[20] I3C_TARG_ADDR_MATCH
    4'b 0011, // index[21] I3C_TARG_ADDR_MASK
    4'b 1111, // index[22] I3C_CTRL_CLK_CONFIG
    4'b 1111, // index[23] I3C_HCI_VERSION
    4'b 1111, // index[24] I3C_HC_CONTROL
    4'b 1111, // index[25] I3C_CONTROLLER_DEVICE_ADDR
    4'b 1111, // index[26] I3C_HC_CAPABILITIES
    4'b 0001, // index[27] I3C_RESET_CONTROL
    4'b 0001, // index[28] I3C_PRESENT_STATE
    4'b 0011, // index[29] I3C_INTR_STATUS
    4'b 0011, // index[30] I3C_INTR_STATUS_ENABLE
    4'b 0011, // index[31] I3C_INTR_SIGNAL_ENABLE
    4'b 0011, // index[32] I3C_INTR_FORCE
    4'b 1111, // index[33] I3C_DAT_SECTION_OFFSET
    4'b 1111, // index[34] I3C_DCT_SECTION_OFFSET
    4'b 0011, // index[35] I3C_RING_HEADERS_SECTION_OFFSET
    4'b 0011, // index[36] I3C_PIO_SECTION_OFFSET
    4'b 0011, // index[37] I3C_EXT_CAPS_SECTION_OFFSET
    4'b 0011, // index[38] I3C_INT_CTRL_CMDS_EN
    4'b 0001, // index[39] I3C_IBI_NOTIFY_CTRL
    4'b 1111, // index[40] I3C_IBI_DATA_ABORT_CTRL
    4'b 1111, // index[41] I3C_DEV_CTX_BASE_LO
    4'b 1111, // index[42] I3C_DEV_CTX_BASE_HI
    4'b 1111, // index[43] I3C_DEV_CTX_SG
    4'b 1111, // index[44] I3C_COMMAND_QUEUE_PORT
    4'b 1111, // index[45] I3C_RESPONSE_QUEUE_PORT
    4'b 1111, // index[46] I3C_IBI_PORT
    4'b 1111, // index[47] I3C_QUEUE_THLD_CTRL
    4'b 1111, // index[48] I3C_DATA_BUFFER_THLD_CTRL
    4'b 1111, // index[49] I3C_QUEUE_SIZE
    4'b 1111, // index[50] I3C_ALT_QUEUE_SIZE
    4'b 0011, // index[51] I3C_PIO_INTR_STATUS
    4'b 0011, // index[52] I3C_PIO_INTR_STATUS_ENABLE
    4'b 0011, // index[53] I3C_PIO_INTR_SIGNAL_ENABLE
    4'b 0011, // index[54] I3C_PIO_INTR_FORCE
    4'b 0111, // index[55] I3C_STBY_EXTCAP_HEADER
    4'b 1111, // index[56] I3C_STBY_CR_CONTROL
    4'b 1111, // index[57] I3C_STBY_CR_DEVICE_ADDR
    4'b 0011, // index[58] I3C_STBY_CR_CAPABILITIES
    4'b 0011, // index[59] I3C_STBY_CR_STATUS
    4'b 1111, // index[60] I3C_STBY_CR_DEVICE_CHAR
    4'b 1111, // index[61] I3C_STBY_CR_DEVICE_PID_LO
    4'b 0111, // index[62] I3C_STBY_CR_INTR_STATUS
    4'b 0111, // index[63] I3C_STBY_CR_INTR_SIGNAL_ENABLE
    4'b 0111, // index[64] I3C_STBY_CR_INTR_FORCE
    4'b 0001, // index[65] I3C_STBY_CR_CCC_CONFIG_GETCAPS
    4'b 1111, // index[66] I3C_STBY_CR_CCC_CONFIG_RSTACT_PARAMS
    4'b 0111, // index[67] I3C_DEBUG_EXTCAP_HEADER
    4'b 1111, // index[68] I3C_QUEUE_STATUS_LEVEL
    4'b 0011, // index[69] I3C_DATA_BUFFER_STATUS_LEVEL
    4'b 1111, // index[70] I3C_PRESENT_STATE_DEBUG
    4'b 0001, // index[71] I3C_MX_ERROR_COUNTERS
    4'b 0111  // index[72] I3C_SCHED_CMDS_DEBUG
  };

endpackage
